### ISSUE TITLE
Wordpress container is unable to authenticate with database

### ISSUE THREAD

**Issue by ItayPodhajcer** [bitnami-labs/aci-templates#6]
Just tried executing the template, and for some reason, the wordpress container is unable to authenticate with the database.

**Error:** `mysql-c ERROR [canConnect] Connection with '[MYSQL_USER]' user is unsuccessful`

**Complete Log (after 2 restarts):**
```
[0m
[0m[1mWelcome to the Bitnami wordpress container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-wordpress[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-wordpress/issues[0m
[0m
[0m[38;5;3mWARN [0m ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at 127.0.0.1:3306
mysql-c ERROR [canConnect] Connection with '[MYSQL_USER]' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '[MYSQL_USER]' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '[MYSQL_USER]' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '[MYSQL_USER]' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '[MYSQL_USER]' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error: 
 ERROR 1156 (08S01): Plugin caching_sha2_password could not be loaded: /opt/bitnami/mysql//opt/bitnami/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

Any ideas what's causing this?

**Comment by ItayPodhajcer** [comment]
Does the wordpress image have an MySQL/MariaDB? as it might be a problem with ACI's containers group usage of `localhost` for communication between containers

**Comment by juan131** [comment]
Hi @ItayPodhajcer 

> Does the wordpress image have an MySQL/MariaDB? as it might be a problem with ACI's containers group usage of localhost for communication between containers

The Bitnami WordPress image doesn't bundle any MariaDB/MySQL database but a "mysql client" instead. It uses that client to connect with the MariaDB/MySQL service which is booted on a different container.

> Just tried executing the template, and for some reason, the wordpress container is unable to authenticate with the database.

What steps did you follow to deploy the ACI template? Did you follow the steps explained in this [README.md file](https://github.com/bitnami-labs/aci-templates/blob/master/wordpress/README.md#deployment-steps)?

**Comment by ItayPodhajcer** [comment]
Hi @juan131 ,
I used the **[Deploy To Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fbitnami-labs%2Faci-templates%2Fmaster%2Fwordpress%2Fazuredeploy.json)** link located [here](https://github.com/bitnami-labs/aci-templates/tree/master/wordpress).
The template itself seems OK, but maybe one of the bitnami images got an unexpected update that broke the template?

**Comment by juan131** [comment]
I was able to reproduce the issue locally using the `docker-compose.yaml` below:

```
version: '2'
services:
  mysql:
    image: 'bitnami/mysql'
    volumes:
      - 'mysql_data:/bitnami/mysql'
    environment:
      - MYSQL_USER=bn_wordpress
      - MYSQL_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mysql
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
```

However, it works without any issue when using MariaDB (instead of MySQL):

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
```

I created a task to investigate what's going on... Thanks so much for reporting the issue.

**Comment by shenyuea** [comment]
same issue

**Comment by juan131** [comment]
Hi @shenyuea 

Did you try with MariaDB (instead of MySQL)?

**Comment by shenyuea** [comment]
i tried to connet from the wordpress container: 
mysql -u bn_wordpress -h  127.0.0.1
ERROR 1156 (08S01): Plugin caching_sha2_password could not be loaded: /opt/bitnami/mysql//opt/bitnami/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory

**Comment by shenyuea** [comment]
according to this issue [https://github.com/creditease-sec/insight/issues/11](url), the lastest mysql using caching_sha2_password as the default auth method rather than mysql_native_password, so it require the sha2 library , which is not installed in the container image.
I made it work，through the following steps：
 1, change the authentication method of the user bn_wordpress from caching_sha2_password to
     mysql_native_password
 2, set the password of user bn_wordpress to null;

**Comment by juan131** [comment]
Hi @shenyuea 

Thanks so much for providing more information about how you could workaround the issue! It'll be very helpful for the team.

We have an internal task created to fix this issue with WordPress but it's not a high priority task since most of our WP solutions use MariaDB as database backend. 

We'll notify you about our progress once we start working on the aforementioned task.

**Comment by sameersbn** [comment]
@shenyuea as mentioned in https://www.akamenskiy.com/fix-wordpress-database-connection-mysql-8/, a workaround for this issue is to add the following config lines ti mysqld

```conf
[mysqld]
default_authentication_plugin=mysql_native_password
```

Therefore as a workaround create a file `my_custom.cnf` with the above config and mount in in the mysql container as shown below.

```yaml
version: '2'
services:
  mysql:
    image: 'bitnami/mysql:8.0'
    volumes:
      - 'mysql_data:/bitnami/mysql'
      - '/path/to/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro'
    environment:
      - MYSQL_USER=bn_wordpress
      - MYSQL_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mysql
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_SCHEME=https
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mysql_data:
    driver: local
  wordpress_data:
    driver: local
```
